apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
          - name: ghcr-secret
      containers:
        - name: backend
          image: ghcr.io/samgliu/stocksense-backend:latest
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: backend-secrets
            - configMapRef:
                name: backend-config
