apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: kafka-pool
  namespace: default
  labels:
    strimzi.io/cluster: kafka
spec:
  replicas: 3
  roles:
    - broker
    - controller
  storage:
    type: ephemeral
