kraft:
  enabled: true
  clusterId: 'VcZLyB1mTSu2QaOJrcSPtA=='

replicaCount: 3

listeners:
  client:
    protocol: PLAINTEXT

auth:
  enabled: false

persistence:
  enabled: true
  size: 5Gi

resources:
  requests:
    cpu: 250m
    memory: 1Gi
  limits:
    cpu: 500m
    memory: 1.5Gi

extraEnvVars:
  - name: KAFKA_CONTROLLER_QUORUM_REQUEST_TIMEOUT_MS
    value: "5000"
  - name: KAFKA_CONTROLLER_SESSION_TIMEOUT_MS
    value: "15000"

service:
  type: LoadBalancer
