apiVersion: v1
kind: Service
metadata:
  name: worker-langgraph
  namespace: default
  labels:
    app: worker-langgraph
spec:
  selector:
    app: worker-langgraph
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
  type: ClusterIP
