apiVersion: v1
kind: Service
metadata:
  name: worker
  namespace: default
  labels:
    app: worker
spec:
  selector:
    app: worker
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
  type: ClusterIP
