apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-config
  namespace: monitoring
data:
  agent.yaml: |
    metrics:
      wal_directory: /tmp/wal
      global:
        scrape_interval: 15s
      configs:
        - name: default
          remote_write:
            - url: https://prometheus-blocks-prod-us-central1.grafana.net/api/prom/push
              basic_auth:
                username: "${GRAFANA_AGENT_USERNAME}"
                password: "${GRAFANA_AGENT_PASSWORD}"

    logs:
      positions:
        filename: /tmp/positions.yaml
      configs:
        - name: default
          clients:
            - url: https://logs-prod-us-central1.grafana.net/loki/api/v1/push
              basic_auth:
                username: "${GRAFANA_AGENT_USERNAME}"
                password: "${GRAFANA_AGENT_PASSWORD}"
          scrape_configs:
            - job_name: varlogs
              static_configs:
                - targets: ["localhost"]
                  labels:
                    job: varlogs
                    __path__: /var/log/**/*.log
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: grafana-agent
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: grafana-agent
  template:
    metadata:
      labels:
        app: grafana-agent
    spec:
      serviceAccountName: default
      containers:
        - name: agent
          image: grafana/agent:v0.37.1
          args:
            - run
            - --config.file=/etc/agent-config/agent.yaml
            - --enable-features=remote-configs-envsubst
          envFrom:
            - secretRef:
                name: grafana-agent-credentials
          volumeMounts:
            - name: config
              mountPath: /etc/agent-config
            - name: varlog
              mountPath: /var/log
            - name: containers
              mountPath: /var/lib/docker/containers
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: grafana-agent-config
        - name: varlog
          hostPath:
            path: /var/log
        - name: containers
          hostPath:
            path: /var/lib/docker/containers
