"""Update Company model with exchange, website, etc.

Revision ID: 1e9437542941
Revises: 812e5055a449
Create Date: 2025-03-29 02:58:07.186268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e9437542941'
down_revision: Union[str, None] = '812e5055a449'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('exchange', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('website', sa.String(), nullable=True))
    op.alter_column('companies', 'ticker',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'ticker',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('companies', 'website')
    op.drop_column('companies', 'exchange')
    # ### end Alembic commands ###
