"""add auto_trade_subscriptions table

Revision ID: 28bca8e8b870
Revises: acb8365186b3
Create Date: 2025-04-13 20:26:42.819333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28bca8e8b870'
down_revision: Union[str, None] = 'acb8365186b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_trade_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('frequency', sa.Enum('hourly', 'daily', 'weekly', name='frequencyenum'), nullable=False),
    sa.Column('risk_tolerance', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risktoleranceenum'), nullable=False),
    sa.Column('wash_sale', sa.Boolean(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auto_trade_subscriptions')
    # ### end Alembic commands ###
