"""Add realized gain

Revision ID: 39ddf687fc73
Revises: 49f023c1004f
Create Date: 2025-04-15 01:30:26.759397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39ddf687fc73'
down_revision: Union[str, None] = '49f023c1004f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mock_transactions', sa.Column('realized_gain', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mock_transactions', 'realized_gain')
    # ### end Alembic commands ###
