"""Update JobStatus: add input field, remove stock_entry_id

Revision ID: 4958461a156c
Revises: 9053e4c1c88d
Create Date: 2025-04-02 02:47:11.503775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4958461a156c'
down_revision: Union[str, None] = '9053e4c1c88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_reports', sa.Column('company_id', sa.UUID(), nullable=True))
    op.add_column('analysis_reports', sa.Column('ticker', sa.String(), nullable=True))
    op.add_column('analysis_reports', sa.Column('exchange', sa.String(), nullable=True))
    op.drop_constraint('analysis_reports_stock_entry_id_fkey', 'analysis_reports', type_='foreignkey')
    op.create_foreign_key(None, 'analysis_reports', 'companies', ['company_id'], ['id'])
    op.drop_column('analysis_reports', 'stock_entry_id')
    op.drop_constraint('job_status_stock_entry_id_fkey', 'job_status', type_='foreignkey')
    op.drop_column('job_status', 'stock_entry_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_status', sa.Column('stock_entry_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('job_status_stock_entry_id_fkey', 'job_status', 'stock_entries', ['stock_entry_id'], ['id'])
    op.add_column('analysis_reports', sa.Column('stock_entry_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'analysis_reports', type_='foreignkey')
    op.create_foreign_key('analysis_reports_stock_entry_id_fkey', 'analysis_reports', 'stock_entries', ['stock_entry_id'], ['id'])
    op.drop_column('analysis_reports', 'exchange')
    op.drop_column('analysis_reports', 'ticker')
    op.drop_column('analysis_reports', 'company_id')
    # ### end Alembic commands ###
