"""Add analysis_reports table and link to job_status

Revision ID: 6c46f9fee5ea
Revises: 5606a53c4114
Create Date: 2025-04-02 01:46:12.764512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6c46f9fee5ea'
down_revision: Union[str, None] = '5606a53c4114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('stock_entry_id', sa.UUID(), nullable=False),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('time_horizon', sa.String(), nullable=True),
    sa.Column('prediction_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('insights', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_entry_id'], ['stock_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('job_status', sa.Column('stock_entry_id', sa.UUID(), nullable=True))
    op.add_column('job_status', sa.Column('analysis_report_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'job_status', 'analysis_reports', ['analysis_report_id'], ['id'])
    op.create_foreign_key(None, 'job_status', 'stock_entries', ['stock_entry_id'], ['id'])
    op.create_foreign_key(None, 'job_status', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'job_status', type_='foreignkey')
    op.drop_constraint(None, 'job_status', type_='foreignkey')
    op.drop_constraint(None, 'job_status', type_='foreignkey')
    op.drop_column('job_status', 'analysis_report_id')
    op.drop_column('job_status', 'stock_entry_id')
    op.drop_table('analysis_reports')
    # ### end Alembic commands ###
