"""Change input column to JSONB in job_status

Revision ID: 9053e4c1c88d
Revises: 6c46f9fee5ea
Create Date: 2025-04-02 02:10:02.214791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9053e4c1c88d'
down_revision: Union[str, None] = '6c46f9fee5ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_status', sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_status', 'input')
    # ### end Alembic commands ###
