"""refactor stock entry fields

Revision ID: a2811ca83f6b
Revises: cc4dd3166448
Create Date: 2025-03-27 02:07:15.217560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2811ca83f6b'
down_revision: Union[str, None] = 'cc4dd3166448'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_entries', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('stock_entries', sa.Column('model_used', sa.String(), nullable=True))
    op.add_column('stock_entries', sa.Column('source_type', sa.String(), nullable=True))
    op.drop_column('stock_entries', 'gemini_summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_entries', sa.Column('gemini_summary', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('stock_entries', 'source_type')
    op.drop_column('stock_entries', 'model_used')
    op.drop_column('stock_entries', 'summary')
    # ### end Alembic commands ###
