"""Fix TradeReport FK

Revision ID: bc4b7640b9a7
Revises: fd2ef39a8ba1
Create Date: 2025-04-14 04:59:40.696157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc4b7640b9a7'
down_revision: Union[str, None] = 'fd2ef39a8ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade_reports', 'subscription_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade_reports', 'subscription_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
