"""Add AutoTrader mock tables

Revision ID: fd2ef39a8ba1
Revises: 6306c05edf6e
Create Date: 2025-04-13 23:20:12.137807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd2ef39a8ba1'
down_revision: Union[str, None] = '6306c05edf6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mock_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('shares', sa.Integer(), nullable=False),
    sa.Column('average_cost', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['mock_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mock_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('action', sa.Enum('BUY', 'SELL', 'HOLD', name='tradedecision'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['mock_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=True),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('decision', sa.Enum('BUY', 'SELL', 'HOLD', name='tradedecision'), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['auto_trade_subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_reports')
    op.drop_table('mock_transactions')
    op.drop_table('mock_positions')
    op.drop_table('mock_accounts')
    # ### end Alembic commands ###
