name: Deploy to Render (Backend & Worker)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Install Render CLI (latest)
        run: |
          curl -L https://github.com/render-oss/cli/releases/latest/download/cli_linux_amd64.tar.gz -o render.tar.gz
          tar -xzf render.tar.gz
          sudo mv render /usr/local/bin/

      - name: Deploy all services from render.yaml
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          CI: true
        run: render blueprint deploy --yes
