name: Deploy Terraform

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'terraform/lambda/**'
      - 'terraform/*.tf'
      - 'terraform/**'
      - '.github/workflows/deploy-terraform.yaml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function:
          - name: scraper
            runtime: node
          - name: gcs
            runtime: python

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        if: matrix.function.runtime == 'node'
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup Python
        if: matrix.function.runtime == 'python'
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        working-directory: terraform/lambda/${{ matrix.function.name }}
        run: |
          if [[ "${{ matrix.function.runtime }}" == "node" ]]; then
            npm install
          elif [[ "${{ matrix.function.runtime }}" == "python" ]]; then
            pip install -r requirements.txt -t dist/
          fi

      - name: Build Lambda
        working-directory: terraform/lambda/${{ matrix.function.name }}
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload Lambda zip
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.function.name }}-zip
          path: terraform/lambda/${{ matrix.function.name }}/dist/index.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download scraper artifact
        uses: actions/download-artifact@v4
        with:
          name: scraper-zip
          path: terraform/lambda/scraper/dist

      - name: Download gcs artifact
        uses: actions/download-artifact@v4
        with:
          name: gcs-zip
          path: terraform/lambda/gcs/dist

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

  terraform-infra:
    name: Terraform Apply (Cloudflare + AWS)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform

    env:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
