name: Publish Worker Docker Image

on:
  push:
    branches: [main]
    paths:
      - 'worker-langgraph/**'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build & Push Worker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push worker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/stocksense-worker:latest ./worker-langgraph
          docker push ghcr.io/${{ github.repository_owner }}/stocksense-worker:latest
